<?php

namespace App\Feeds\Vendors\ULE;

use App\Feeds\Feed\FeedItem;
use App\Feeds\Processor\SitemapHttpProcessor;
use App\Feeds\Utils\Data;
use Illuminate\Support\Facades\Storage;

class Vendor extends SitemapHttpProcessor
{
    protected array $first = ['https://www.uline.com/sitemap-us-product.xml.gz'];
    protected const USE_PROXY = true;
    protected const CHUNK_SIZE = 2;
    protected array $headers = [
        'Connection' => 'keep-alive',
        'Accept' => '*/*',
    ];
    public function afterProcess()
    {
        parent::afterProcess(); // TODO: Change the autogenerated stub
    }

    public array $custom_products = [
        'https://www.uline.com/Product/Detail/S-12261/White-Block-Poly-Bags/1-1-2-x-2-2-Mil-White-Block-Reclosable-Bags',
        'https://www.uline.com/Product/Detail/S-10567/Retail-Boxes/Gable-Boxes-4-x-2-1-2-x-2-1-2-White',
        'https://www.uline.com/Product/Detail/H-6761-54A/Industrial-Wire-Shelving/Chrome-Wire-Shelving-Add-On-Unit-60-x-30-x-54',
        'https://www.uline.com/Product/Detail/H-1006-NOSE/Hand-Trucks/Nose-Plate-for-Magliner-Hand-Truck-18-x-7-1-2',
        'https://www.uline.com/Product/Detail/S-10588P/Bubble-Rolls/Bubble-Mask-Roll-24-x-125-1-2-Perforate',
        'https://www.uline.com/Product/Detail/H-1006-NOSE/Hand-Trucks/Nose-Plate-for-Magliner-Hand-Truck-18-x-7-1-2',
        'https://www.uline.com/Product/Detail/H-7786/Office-Tables/Collaboration-Table-Single-Workstation-60-x-30',
    ];

    public function getProductsLinks( Data $data, string $url ): array
    {
        $content = $this->getDownloader()->get( $url );
        $file_name = preg_replace( '/(.*\/)/', '', $url );
        Storage::disk( 'temp' )->put( $file_name, $content );
        $gz_file = gzopen( Storage::path( 'temp' ) . '\\' . $file_name, 'r');
        $xml = gzread( $gz_file, 100000000 );
        gzclose( $gz_file );
        Storage::disk( 'temp' )->delete( $file_name );

        $data = new Data( $xml );
        return parent::getProductsLinks($data, $url);
    }

//    protected function isValidFeedItem(FeedItem $fi ): bool
//    {
//        return !empty( $fi->getMpn() ) && count( $fi->getImages() ) && $item->getCostToUs() > 0;
//    }
}
